name: Build
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      tag-name:
        type: string
        default: "draft"
      channel:
        type: string
        default: "dev"

env:
  IS_GITHUB_ACTIONS: 1
  CHANNEL: "${{ inputs.channel }}"
  FLUTTER_VERSION: '3.38.5'
  NDK_VERSION: r28c
  UPLOAD_ARTIFACT: "${{ inputs.upload-artifact }}"
  TAG_NAME: "${{ inputs.tag-name }}"
  TARGET_NAME_gz: "Hiddify-Linux-x64-AppImage.tar"
  TARGET_NAME_AppImage: "Hiddify-Linux-x64-AppImage"
  TARGET_NAME_deb: "Hiddify-Debian-x64"
  TARGET_NAME_apk: "Hiddify-Android"
  TARGET_NAME_aab: "Hiddify-Android"
  TARGET_NAME_exe: "Hiddify-Windows-Setup-x64"
  TARGET_NAME_msix: "Hiddify-Windows-x64"
  TARGET_NAME_zip: "Hiddify-Windows-Portable-x64"
  TARGET_NAME_dmg: "Hiddify-MacOS"
  TARGET_NAME_pkg: "Hiddify-MacOS-Installer"
  TARGET_NAME_ipa: "Hiddify-iOS"

jobs:
  test:
    outputs:
      draftBuildCode: ${{ steps.draftBuildCode.outputs.datetime }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      - name: Prepare
        run: make linux-amd64-prepare
      - name: Test
        run: flutter test
      - name: make draftBuildCode
        id: draftBuildCode
        run: echo "datetime=$(date +'%d.%H.%M')" >> $GITHUB_OUTPUT

  build:
    needs: test
    permissions: write-all
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: android-apk
            os: ubuntu-latest
            targets: apk
          - platform: android-aab
            os: ubuntu-latest
            targets: aab
          - platform: windows
            os: windows-latest
            aarch: amd64
            targets: exe,msix,zip
          - platform: linux
            os: ubuntu-22.04
            aarch: amd64
            targets: deb,gz,AppImage
          - platform: macos
            os: macos-15
            aarch: universal
            targets: dmg,pkg

    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Setup Java
        if: startsWith(matrix.platform,'android')
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Android SDK
        if: startsWith(matrix.platform,'android')
        uses: android-actions/setup-android@v3

      - name: Setup dependencies
        run: |
          make ${{ matrix.platform }}-install-deps  
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Prepare for ${{ matrix.platform }}
        run: make ${{ matrix.platform }}-prepare

      - name: Build ${{ matrix.platform }}
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: make ${{ matrix.platform }}-release

      - name: Copy to out Android APK
        if: matrix.platform == 'android-apk'
        run: |
          mkdir -p out
          cp ./build/app/outputs/flutter-apk/app-release.apk out/${TARGET_NAME_apk}-universal.apk || echo "no apk"
          cp ./build/app/outputs/flutter-apk/*arm64-v8a*.apk out/${TARGET_NAME_apk}-arm64.apk || echo "no arm64"

      - name: Copy to out Android AAB
        if: matrix.platform == 'android-aab'
        run: |
          mkdir -p out
          cp ./build/app/outputs/bundle/release/app-release.aab out/hiddify-android-market.aab || echo "no aab"

      - name: Copy to out other platforms
        if: matrix.platform != 'android-apk' && matrix.platform != 'android-aab'
        run: |
          mkdir -p out
          # Здесь можно добавить логику копирования для других платформ, если нужно

      - name: Direct Artifact Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: out/*
          retention-days: 7

  update-draft:
    permissions: write-all
    if: ${{ inputs.upload-artifact }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./all-out/
          merge-multiple: true
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./all-out/*
          name: 'VPN-Build-${{ needs.test.outputs.draftBuildCode }}'
          tag_name: 'v-${{ needs.test.outputs.draftBuildCode }}'
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
